# Generated by Django 2.1.1 on 2018-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wantedly_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
